# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'progress_tracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for progress_tracker
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'


  target 'progress_trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'progress_tracker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for progress_tracker-tvOS

  target 'progress_tracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
