# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'progress_tracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'progress_trackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'progress_tracker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for progress_tracker-tvOS

  target 'progress_tracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
