# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  lane :beta do
    build
    changelog_from_git_commits
    upload_to_testflight
  end

  lane :release do
    build
    upload_to_app_store
  end

  lane :build do
    sync_code_signing(type: "appstore")
    increment_build_number(xcodeproj: "progress_tracker.xcodeproj")
    set_info_plist_value(path: "progress_tracker/Info.plist",
        key: 'NSAppTransportSecurity',
        value: {
           'NSExceptionDomains' => {}
        }
    )
    build_app(
        workspace: "progress_tracker.xcworkspace",
        scheme: "progress_tracker",
        output_directory: "build",
        output_name: "completoo.ipa",
        derived_data_path: "build"
    )
    set_info_plist_value(path: "progress_tracker/Info.plist",
        key: 'NSAppTransportSecurity',
        value: {
           'NSExceptionDomains' => {
               'localhost' => {
                   'NSExceptionAllowsInsecureHTTPLoads' => true
               }
           }
        }
    )
  end
end
