enum AnalyticsEvent {
    ActivitiesPageOpenFriendsActivities =
        "activitiesPage_openFriendsActivities",
    ActivitiesPageOpenMyActivities = "activitiesPage_openMyActivities",
    ActivitiesPageOpenUser = "activitiesPage_openUser",
    AddGymExerciseEntryFormCancel = "addGymExerciseEntryForm_cancel",
    AddGymExerciseEntryFormSubmit = "addGymExerciseEntryForm_submit",
    AddNumericalProgressFormSubmit = "addNumericalProgressForm_submit",
    AddNumericalProgressFormCancel = "addNumericalProgressForm_cancel",
    ApproveDifficultyPickerCancel = "approveDifficultyPicker_cancel",
    ApproveDifficultyPickerSubmit = "approveDifficultyPicker_submit",
    ArchivePageOpenApprovedTrackables = "archivePage_openApprovedTrackables",
    ArchivePageOpenRejectedTrackables = "archivePage_openRejectedTrackables",
    ArchivePageOpenExpiredTrackables = "archivePage_openExpiredTrackables",
    FacebookLoginPageCancel = "facebookLoginPage_cancel",
    FacebookLoginPageSubmit = "facebookLoginPage_submit",
    FacebookShareAppPageCancel = "facebookShareAppPage_cancel",
    FacebookShareAppPageSubmit = "facebookShareAppPage_submit",
    FacebookShareTrackablePageCancel = "facebookShareTrackablePage_cancel",
    FacebookShareTrackablePageSubmit = "facebookShareTrackablePage_submit",
    FriendsPageOpenUser = "friendsPage_openUser",
    FriendsPageSetMuted = "friendsPage_setMuted",
    GlobalNavOpenActivities = "globalNav_openActivities",
    GlobalNavOpenFriends = "globalNav_openFriends",
    GlobalNavOpenLeaders = "globalNav_openLeaders",
    GlobalNavOpenPendingReview = "globalNav_openPendingReview",
    GlobalNavOpenProfile = "globalNav_openProfile",
    LeadersPageOpenGlobalChart = "leadersPage_openGlobalChart",
    LeadersPageOpenFriendsChart = "leadersPage_openFriendsChart",
    LeadersPageOpenUser = "leadersPage_openUser",
    ListLoadMore = "list_loadMore",
    ListRefresh = "list_refresh",
    LoginBtnClick = "loginBtn_click",
    LoginPageSkip = "loginPage_skip",
    NewTrackablePickerCancel = "newTrackablePicker_cancel",
    NewTrackablePickerSubmit = "newTrackablePicker_submit",
    PendingReviewPageOpenGlobalTrackables =
        "pendingReviewPage_openGlobalTrackables",
    PendingReviewPageOpenFriendsTrackables =
        "pendingReviewPage_openFriendsTrackables",
    PendingReviewPageOpenMyTrackables =
        "pendingReviewPage_openMyTrackables",
    PendingReviewPageOpenUser = "pendingReviewPage_openUser",
    ProfileFormClose = "profileForm_close",
    ProfileFormLogout = "profileForm_logout",
    ProfileFormRemoveAvatar = "profileForm_removeAvatar",
    ProfileFormSetAvatar = "profileForm_setAvatar",
    ProfileFormSetName = "profileForm_setName",
    ProfilePageAddTrackable = "profilePage_addTrackable",
    ProfilePageEditProfile = "profilePage_editProfile",
    ProfilePageOpenActiveTrackables = "profilePage_openActiveTrackables",
    ProfilePageOpenArchive = "profilePage_openArchive",
    ProfilePageReportUser = "profilePage_reportUser",
    ProofPickerCancel = "proofPicker_cancel",
    ProofPickerSubmit = "proofPicker_submit",
    RejectReasonPickerCancel = "rejectReasonPicker_cancel",
    RejectReasonPickerSubmit = "rejectReasonPicker_submit",
    ReportReasonPickerCancel = "reportReasonPicker_cancel",
    ReportReasonPickerSubmit = "reportReasonPicker_submit",
    ShareProvedGoalPopupAccept = "shareProvedGoalPopup_accept",
    ShareProvedGoalPopupDecline = "shareProvedGoalPopup_decline",
    TrackableFormClose = "trackableForm_close",
    TrackableFormSubmit = "trackableForm_submit",
    TrackableFormToggleAdvanced = "trackableForm_toggleAdvanced",
    TrackableAddProgress = "TrackableAddProgress",
    TrackableAggregate = "trackable_aggregate",
    TrackableUnaggregate = "trackable_unaggregate",
    TrackableCancelAggregation = "trackable_cancelAggregation",
    TrackableSubmitAggregation = "trackable_submitAggregation",
    TrackableEdit = "trackable_edit",
    TrackableProve = "trackable_prove",
    TrackableRemove = "trackable_remove",
    TrackableReorder = "trackable_reorder",
    TrackableReview = "trackable_review",
    TrackableSelect = "trackable_select",
    TrackableSetExpanded = "trackable_setExpanded",
    TrackableSetTaskDone = "trackable_setTaskDone",
}

export default AnalyticsEvent;
